<!DOCTYPE html>
<html>
<head>
    <title>Terms Of Use</title>
    <link rel='stylesheet' href='../style/theme.css'>
</head>
<body>
    <?php include('../includes/header.php')?>
    <?php include('../includes/navigation.php'); ?>
    <div class="page-wrapper" style="display: block; max-width: 1170px;">
        <div class="page-title-wrapper"><h1 class="page-title">
            <span class="base">Terms Of Use</span></h1>
    </div>
<p><b>USE OF SITE</b></p>
<p>1.1&nbsp;&nbsp; Please read the following Terms of Use carefully before you purchase from ChocoSmith Online store (“our/this Website”). By accessing this Website, you agree to be bound by these Terms of Use and by any modifications, alterations or updates herein. If you do not agree with these Terms of Use, you are advised not to continue using this Website.</p>
<p>1.2&nbsp;&nbsp; We reserve the right at any time in our sole discretion to modify, alter or otherwise update these Terms of Uses at any time without further notice. You are encouraged to regularly review the Terms of Use each time you use this Website. Your use of this Website following any such modification constitutes your agreement to follow and be bound by the Terms of Use as modified.</p>
<p>1.3&nbsp;&nbsp; You are responsible for all access to this Website through your Internet connection and for bringing these Terms of Use to the attention of all such persons.</p>
<p>1.4&nbsp;&nbsp; You shall not in any way use this Website or submit to us or to this Website or to any user of this Website anything which in any respect:</p>
<p>1.4.1&nbsp;&nbsp; is in breach of any law, statute, regulation or byelaw of any applicable jurisdiction;</p>
<p>1.4.2&nbsp;&nbsp; is fraudulent, criminal or unlawful;</p>
<p>1.4.3&nbsp;&nbsp; is inaccurate or out-of-date;</p>
<p>1.4.4&nbsp;&nbsp; may be obscene, indecent, pornographic, vulgar, profane, racist, sexist, discriminatory, offensive, derogatory, harmful, harassing, threatening, embarrassing, malicious, abusive, hateful, menacing, defamatory, untrue or political;</p>
<p>1.4.5&nbsp;&nbsp; impersonates any other person or body or misrepresents a relationship with any person or body;</p>
<p>1.4.6&nbsp;&nbsp; may infringe or breach the copyright or any intellectual property rights (including without limitation copyright, trade mark rights and broadcasting rights) or privacy or other rights of us or any third party;</p>
<p>1.4.7&nbsp;&nbsp; may be contrary to our interests;</p>
<p>1.4.8&nbsp;&nbsp; is contrary to any specific rule or requirement that we stipulate on the Website in relation to a particular part of the Website or the Website generally; or</p>
<p>1.4.9&nbsp;&nbsp; involves your use, delivery or transmission of any viruses, unsolicited emails or any other computer programming routines that are intended to damage, detrimentally interfere with, surreptitiously intercept or expropriate any system, data or personal information.</p>
<p>1.5&nbsp;&nbsp; Our policy does not allow us to accept or to consider unconsolidated ideas, including ideas for new advertising and campaigns, marketing strategies, new or improved products, technologies, services, processes, materials, or new product names. Accordingly, while we value your feedback, this policy is necessary in order to avoid the possibility of future misunderstandings should our business activities bear coincidental similarities with the creative ideas submitted by user (“the Submissions”). Please do not send us the Submissions. If, at our request, you send certain specific Submissions or without a request from us you send Submissions or other materials, whether online, by email, by postal mail or other transmission may say, (1) your Submissions will automatically become the property of ChocoSmith, without any compensation to you; (2) ChocoSmith will have no obligation to return your Submissions to you or respond to you in any way; (3) ChocoSmith will have no obligation to keep your Submissions confidential; and (4) ChocoSmith may use your Submissions for any purpose whatsoever, including giving your Submissions to others.<br> 
<br> 1.6&nbsp;&nbsp; Commentary and other materials posted on this Website are not intended to amount to advise on which reliance should be placed. We therefore disclaim all liability and responsibility arising from any reliance placed on such materials by any visitor to the Website, or by anyone who may be informed of any of its contents.</p>
<p>1.7&nbsp;&nbsp; You agree to comply at all times with any instructions for use of this Website which we make from time to time.</p>
<p>&nbsp;</p>
<p><b>TRADEMARK</b></p>
<p>1.8&nbsp;&nbsp; The ChocoSmith name, logo, all related names, design marks and slogans are the trademarks or service marks of us or our licensors and you are prohibited from using any of the names and logos and all related names, design marks and slogans appearing throughout this Website without permission from the trademark owner, except as permitted by applicable law.</p>
<p>&nbsp;</p><p><b>INTELLECTUAL PROPERTY</b></p>
<p>1.9&nbsp;&nbsp; We are the owner or the licensee of all intellectual property rights in the Website, and in the material published on it. Those works are protected by copyright laws and treaties around the world. All such rights are reserved.</p>
<p>1.10&nbsp;&nbsp; You may reprint and download extracts, of any page (s) from the Website for non-commercial, non-public, personal use only and you may draw the attention of others within your organization to material posted on this Website.</p>
<p>1.11&nbsp;&nbsp; ChocoSmith has included sample pictures on certain pages within this Website, to demonstrate the characteristic, nature and description of our goods and products. You may download, reprint and manipulate the sample pictures for this purpose, but you may not crop or change the composition of the image or use the image for commercial purpose.</p>
<p>1.12&nbsp;&nbsp; You must not modify the paper or digital copies of any materials you have printed off or downloaded in any way and you must use any illustrations, photographs, video or audio sequences or any graphics separately from any accompanying text.</p>
<p>1.13&nbsp;&nbsp; You must not use any part of materials on this Website for commercial purposes without obtaining a license to do so from us or our licensors.</p>
<p>1.14&nbsp;&nbsp; If you print off, copy or download any part of this Website in breach of these Terms of Use, your right to view and use this Website will cease immediately and you must, at our option, destroy any copies of the materials in your possession whether electronic or printed format.</p>
<p>&nbsp;</p>
<p><b>PRIVACY POLICY</b></p>
<p>1.15&nbsp;&nbsp; Please review our <a href="../extras/policy.php">privacy policy</a>, which also governs your visit to this site, to understand our practices.</p>
<p>&nbsp;</p><p><b>AVAILABILITY OF THE WEBSITE, SECURITY AND ACCURACY</b></p>
<p>1.16&nbsp;&nbsp; Whilst we endeavour to make the upkeep of this Website to be available 24 hours a day, we cannot be liable if for any reason this Website is unavailable for any time or for any period. We make no warranty that your access to this Website will be uninterrupted, timely or error-free. Due to the nature of the Internet, this cannot be guaranteed. In addition, we may occasionally need to carry out repairs, maintenance or introduce new facilities and functions.</p>
<p>1.17&nbsp;&nbsp; Access to this Website may be suspended or withdrawn to or from you personally or all users temporarily or permanently at any time and without notice. We may also impose restrictions on the length and manner of usage of any part of this Website for any reason. If we impose restrictions on you personally, you must not attempt to use this Website under any other name or user.</p>
<p>1.18&nbsp;&nbsp; We do not warrant that this Website will be compatible with all hardware and software which you may use. We shall not be liable for damage to, or viruses or other code that may affect, any computer equipment, software, data or other property as a result of your access to or use of this Website or your obtaining any material from, or as a result of using, this Website. We shall also not be liable for the actions of third parties.</p>
<p>1.19&nbsp;&nbsp; We may change or update this Website and anything described in it without prior notice.</p>
<p>1.20&nbsp;&nbsp; Whilst we endeavour to ensure that information and materials on this Website are correct, no warranty or representation, expressed or implied, is given that they are complete and accurate as there occasionally may be information and materials on this Website that contains typographical errors, inaccuracies or omissions that may relate to product descriptions, pricing, promotions, offers, and availability. In addition, no warranty or representation, expressed or implied, is given that they are complete, accurate, up to date, fit for a particular purpose. Subject to Clause 4.4 of the Terms and Conditions, we reserve the absolute right to correct any errors, inaccuracies, omissions and to change or update information or cancel orders if any information or materials on this Website is inaccurate at any time without prior notice. ChocoSmith does not, however, guarantee that any errors, inaccuracies or omissions will be corrected.</p><p>&nbsp;</p>
<p><b>REGISTRATION FOR THE SERVICE</b></p>
<p>1.21&nbsp;&nbsp; If you would like to submit an order to this Website to purchase one of the products listed on the Website, you can choose either to register an account on this Website. To register an account, you will be required to access on this Website through the “My User Account” part of this Website. To register you need to provide us with your name, postcode and email address and possibly some other personal information. See our Privacy Policy for more details about this.</p>
<p>1.22&nbsp;&nbsp; Once you register with this Website, you will be asked to create a username for, and allocate a password to your Account. You are responsible for maintaining the confidentiality of your member identification and password information for your Account, and for restricting access to your computer. You shall immediately notify us if any unauthorised third party becomes aware of that password or if there is any unauthorised use of your email address or your Account or any breach of security known to you. You agree that any person to whom your username or password is disclosed is authorised to act as your agent for the purposes of using (and/or transacting via) your Account. You further agree to accept responsibility for all activities and/or transactions that occur under your member identification and password for your Account.</p>
<p>1.23&nbsp;&nbsp; You must be registered with a valid personal email address that you access regularly, so that, among other things, administration emails can be sent to you. Any Accounts which have been registered with someone else’s email address or with temporary email addresses may be closed without notice. We may require you to validate Accounts at registration or if we believe you have been using an invalid email address.</p>
<p>1.24&nbsp;&nbsp; We reserve the right to close your Account, if you are found to have any intentions or actions that disrupts the Website in any way.</p>
<p>1.25&nbsp;&nbsp; When you register for an Account, and whenever you log on to your Account thereafter, you have the option to sign up to receive, and to opt out of receiving information emails (such as newsletters or information on offers etc.). You are able to unsubscribe from such information emails at any time by logging in to your Account or by sending an email to unsubscribe.</p>
<p>1.26&nbsp;&nbsp; Although we save the information relating to any order that you submit to this Website to purchase one of the products listed on the Website, you are unable to directly retrieve this information for security reasons. You may access this information by logging in to your Account. You will be able to view information relating to your completed, open or recently dispatched orders and manage and save your address information, any bank details and any newsletter to which you may have subscribed.</p>
<p>&nbsp;</p>
<p><b>DISCLAIMER</b></p>
<p>1.27&nbsp;&nbsp; The materials on this Website are provided “as is” and “as available” basis. ChocoSmith makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Furthermore, ChocoSmith does not warrant that the functions performed by the Website or the service will be uninterrupted, timely, secure or error-free, or that defects in the Website or the service will be corrected. ChocoSmith also does not warrant the accuracy or completeness of the content, or that any errors in the content will be corrected.</p>
<p>1.28&nbsp;&nbsp; In no event will ChocoSmith be liable for any damages whatsoever, including, but not limited to any direct, incidental, consequential, special, exemplary or other indirect damages arising out of (1) the use of or inability to use this Website or the service or the materials therein; (2) any transaction conducted through or facilitated by the Website; (3) any claim attributable to errors, omissions, or other inaccuracies in this Website, the service, or the materials therein; (4) unauthorised access to or alteration of your transmissions or data, or (5) any other matter relating to this Website, the service or the materials therein, even if Bata has been advised of the possibility of such damages. If you are dissatisfied with the Website, the service and the materials therein, or with the Terms of Use, your sole and exclusive remedy is to discontinue using this Website.</p>
<p>&nbsp;</p><p><b>THIRD PARTIES WEBSITE</b></p>
<p>1.29&nbsp;&nbsp; This Website may contain links to other websites that are not under the control of ChocoSmith (unless we are the provider of those linked sites). ChocoSmith has no responsibility for the contents of any such linked websites nor does linking constitute an endorsement by ChocoSmith of the site. Links are provided solely for the convenience and information of the user and the use of any such linked website is at the user’s own risk.</p>
<p>1.30&nbsp;&nbsp; You must not without our permission mirror or frame the home page or any other page of this Website onto your own or another person’s website.</p>
<p>1.31&nbsp;&nbsp; We hereby grant to you a revocable, non-exclusive, royalty-free right to provide a link from your website to the home page of this Website, provided that you do so in a fair and legal way without damaging our reputation or taking advantage of it. In particular:</p>
<p>1.31.1&nbsp;&nbsp; you shall not make any warranties or representations about us, our services or our policies without our prior consent;</p>
<p>1.31.2&nbsp;&nbsp; you shall not say anything that is false, misleading, derogatory or offensive about us or our services or policies; and</p>
<p>1.31.3&nbsp;&nbsp; you shall not explicitly or implicitly suggest that we have endorsed your site or are associated with it where this is not the case.</p>
<p>&nbsp;&nbsp;</p><p><b>MALAYSIA LAW AND JURISDICTION</b></p><p>1.32 These Terms of Use and your use of this Website (and all non-contractual relationships arising out of or connected to it or them) shall be governed by and construed in accordance with Malaysia law without regard to its conflict of law provisions. You submit to the exclusive jurisdiction of the Malaysia courts to settle any dispute which may arise under these Terms of Use.</p>
<p>&nbsp;</p>
</div>
    <?php include('../includes/footer.php'); ?>
</body>
</html>